apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  storageClassName: {{ .Values.storage.className }}
  claimRef:
    name: {{ .Release.Name }}-pvc
    namespace: {{ .Release.Namespace }}